project:
  type: website
  output-dir: docs

website:
  title: "Capstone Project: K-Means Clustering on Retail Data"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data.qmd
        text: Data
      - href: methods.qmd
        text: Methods
      - href: results.qmd
        text: Results
      - href: about.qmd
        text: Team

format:
  html:
    theme: cosmo
    toc: true
